<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_model extends CI_Model
{

    public $table = 'produk';
    public $id = 'id_produk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_kategori()
    {
        return $this->db->get('kategori')->result();
    }
    function get_status()
    {
        return $this->db->get('status')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
     function get_id_kategori($id)
    {
        $this->db->where('nama_kategori', $id);
        return $this->db->get('kategori')->row();
    }
     function get_id_status($id)
    {
        $this->db->where('nama_status', $id);
        return $this->db->get('status')->row();
    }
    
 
    // get data with limit and search
    function get_limit_data() {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('produk.* , kategori.* , status.*');
        $this->db->join('kategori' , 'kategori.id_kategori = produk.kategori_id' , 'Left');
        $this->db->join('status' , 'status.id_status = produk.status_id' , 'Left');
        $this->db->where('status_id','1');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Produk_model.php */
/* Location: ./application/models/Produk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-12-24 11:22:38 */
/* http://harviacode.com */